
var FlightSearchBoxConf = {
		data: {
			"m亚洲/大洋洲": {
				charSort: true,
				cityList: [{
					"char": "城市",
					clshct: true,
					list: [{
						name: "香港",
						country: "中国香港",
						code: "HKG"
					}, {
						name: "新加坡",
						country: "新加坡",
						code: "SIN"
					}, {
						name: "首尔",
						country: "韩国",
						code: "SEL"
					}, {
						name: "曼谷",
						country: "泰国",
						code: "BKK"
					}, {
						name: "吉隆坡",
						country: "马来西亚",
						code: "KUL"
					}, {
						name: "东京",
						country: "日本",
						code: "TYO"
					}, {
						name: "台北",
						country: "中国台湾",
						code: "TPE"
					}, {
						name: "悉尼",
						country: "澳大利亚",
						code: "SYD"
					}, {
						name: "澳门",
						country: "中国澳门",
						code: "MFM"
					}, {
						name: "普吉",
						country: "泰国",
						code: "HKT"
					}, {
						name: "墨尔本",
						country: "澳大利亚",
						code: "MEL"
					}, {
						name: "胡志明市",
						country: "越南",
						code: "SGN"
					}, {
						name: "大阪",
						country: "日本",
						code: "OSA"
					}, {
						name: "巴厘岛",
						country: "印度尼西亚",
						code: "DPS"
					}, {
						name: "马尼拉",
						country: "菲律宾",
						code: "MNL"
					}, {
						name: "河内",
						country: "越南",
						code: "HAN"
					}, {
						name: "加德满都",
						country: "尼泊尔",
						code: "KTM"
					}, {
						name: "金边",
						country: "柬埔寨",
						code: "PNH"
					}, {
						name: "雅加达",
						country: "印度尼西亚",
						code: "JKT"
					}, {
						name: "马累",
						country: "马尔代夫",
						code: "MLE"
					}, {
						name: "暹粒",
						country: "柬埔寨",
						code: "REP"
					}, {
						name: "迪拜",
						country: "阿拉伯联合酋长国",
						code: "DXB"
					}, {
						name: "釜山",
						country: "韩国",
						code: "PUS"
					}, {
						name: "名古屋",
						country: "日本",
						code: "NGO"
					}, {
						name: "奥克兰",
						country: "新西兰",
						code: "AKL"
					}, {
						name: "布里斯班",
						country: "澳大利亚",
						code: "BNE"
					}, {
						name: "槟城",
						country: "马来西亚",
						code: "PEN"
					}, {
						name: "高雄",
						country: "中国台湾",
						code: "KHH"
					}, {
						name: "新德里",
						country: "印度",
						code: "DEL"
					}, {
						name: "济州岛",
						country: "韩国",
						code: "CJU"
					}]
				}],
				title: "亚洲/大洋洲热门城市",
				desc: "可直接输入中文名/拼音/英文名/三字码",
				cls: "inter"
			},
			"m美洲": {
				charSort: true,
				cityList: [{
					"char": "城市",
					clshct: true,
					list: [{
						name: "纽约",
						country: "美国",
						code: "NYC"
					}, {
						name: "洛杉矶",
						country: "美国",
						code: "LAX"
					}, {
						name: "多伦多",
						country: "加拿大",
						code: "YTO"
					}, {
						name: "温哥华",
						country: "加拿大",
						code: "YVR"
					}, {
						name: "旧金山",
						country: "美国",
						code: "SFO"
					}, {
						name: "芝加哥",
						country: "美国",
						code: "CHI"
					}, {
						titles: "华盛顿（华盛顿哥伦比亚特区）",
						name: "华盛顿",
						country: "美国",
						code: "WAS"
					}, {
						name: "西雅图",
						country: "美国",
						code: "SEA"
					}, {
						name: "波士顿",
						country: "美国",
						code: "BOS"
					}, {
						name: "底特律",
						country: "美国",
						code: "DTT"
					}, {
						name: "亚特兰大",
						country: "美国",
						code: "ATL"
					}, {
						name: "蒙特利尔",
						country: "加拿大",
						code: "YMQ"
					}, {
						name: "休斯敦",
						country: "美国",
						code: "HOU"
					}, {
						name: "火奴鲁鲁",
						country: "美国",
						code: "HNL"
					}, {
						name: "达拉斯",
						country: "美国",
						code: "DFW"
					}, {
						name: "拉斯维加斯",
						country: "美国",
						code: "LAS"
					}, {
						name: "费城",
						country: "美国",
						code: "PHI"
					}, {
						titles: "圣保罗（巴西）",
						name: "圣保罗",
						country: "巴西",
						code: "SAO"
					}, {
						name: "明尼阿波利斯",
						country: "美国",
						code: "MSP"
					}, {
						name: "渥太华",
						country: "加拿大",
						code: "YOW"
					}, {
						name: "凤凰城",
						country: "美国",
						code: "PHX"
					}, {
						name: "墨西哥城",
						country: "墨西哥",
						code: "MEX"
					}, {
						name: "迈阿密",
						country: "美国",
						code: "MIA"
					}, {
						name: "丹佛",
						country: "美国",
						code: "DEN"
					}, {
						name: "奥兰多",
						country: "美国",
						code: "ORL"
					}, {
						name: "卡尔加里",
						country: "加拿大",
						code: "YYC"
					}, {
						name: "埃德蒙顿",
						country: "加拿大",
						code: "YEA"
					}, {
						name: "布宜诺斯艾利斯",
						country: "阿根廷",
						code: "BUE"
					}, {
						name: "里约热内卢",
						country: "巴西",
						code: "RIO"
					}, {
						name: "匹兹堡",
						country: "美国",
						code: "PIT"
					}]
				}],
				title: "美洲热门城市",
				desc: "可直接输入中文名/拼音/英文名/三字码",
				cls: "inter"
			},
			"m欧洲": {
				charSort: true,
				cityList: [{
					"char": "城市",
					clshct: true,
					list: [{
						name: "伦敦",
						country: "英国",
						code: "LON"
					}, {
						name: "巴黎",
						country: "法国",
						code: "PAR"
					}, {
						name: "法兰克福",
						country: "德国",
						code: "FRA"
					}, {
						name: "莫斯科",
						country: "俄罗斯",
						code: "MOS"
					}, {
						name: "阿姆斯特丹",
						country: "荷兰",
						code: "AMS"
					}, {
						titles: "罗马（意大利）",
						name: "罗马",
						country: "意大利",
						code: "ROM"
					}, {
						name: "米兰",
						country: "意大利",
						code: "MIL"
					}, {
						name: "马德里",
						country: "西班牙",
						code: "MAD"
					}, {
						name: "慕尼黑",
						country: "德国",
						code: "MUC"
					}, {
						name: "柏林",
						country: "德国",
						code: "BER"
					}, {
						name: "斯德哥尔摩",
						country: "瑞典",
						code: "STO"
					}, {
						name: "伊斯坦布尔",
						country: "土耳其",
						code: "IST"
					}, {
						titles: "伯明翰（英国）",
						name: "伯明翰",
						country: "英国",
						code: "BHX"
					}, {
						titles: "巴塞罗那(西班牙)",
						name: "巴塞罗那",
						country: "西班牙",
						code: "BCN"
					}, {
						name: "雅典",
						country: "希腊",
						code: "ATH"
					}, {
						name: "哥本哈根",
						country: "丹麦",
						code: "CPH"
					}, {
						name: "苏黎世",
						country: "瑞士",
						code: "ZRH"
					}, {
						name: "布鲁塞尔",
						country: "比利时",
						code: "BRU"
					}, {
						name: "赫尔辛基",
						country: "芬兰",
						code: "HEL"
					}, {
						name: "爱丁堡",
						country: "英国",
						code: "EDI"
					}, {
						name: "维也纳",
						country: "奥地利",
						code: "VIE"
					}, {
						titles: "格拉斯哥（英国）",
						name: "格拉斯哥",
						country: "英国",
						code: "GLA"
					}, {
						name: "日内瓦",
						country: "瑞士",
						code: "GVA"
					}, {
						name: "圣彼得堡",
						country: "俄罗斯",
						code: "LED"
					}, {
						titles: "都柏林(爱尔兰)",
						name: "都柏林",
						country: "爱尔兰",
						code: "DUB"
					}, {
						name: "汉堡",
						country: "德国",
						code: "HAM"
					}, {
						name: "杜塞尔多夫",
						country: "德国",
						code: "DUS"
					}, {
						name: "布拉格",
						country: "捷克",
						code: "PRG"
					}, {
						name: "布达佩斯",
						country: "匈牙利",
						code: "BUD"
					}, {
						name: "基辅",
						country: "乌克兰",
						code: "IEV"
					}]
				}],
				title: "欧洲热门城市",
				desc: "可直接输入中文名/拼音/英文名/三字码",
				cls: "inter"
			},
			"m非洲": {
				charSort: true,
				cityList: [{
					"char": "城市",
					clshct: true,
					list: [{
						name: "开罗",
						country: "埃及",
						code: "CAI"
					}, {
						name: "约翰内斯堡",
						country: "南非",
						code: "JNB"
					}, {
						name: "内罗毕",
						country: "肯尼亚",
						code: "NBO"
					}, {
						name: "开普敦",
						country: "南非",
						code: "CPT"
					}, {
						name: "毛里求斯",
						country: "毛里求斯",
						code: "MRU"
					}, {
						name: "拉各斯",
						country: "尼日利亚",
						code: "LOS"
					}, {
						name: "喀土穆",
						country: "苏丹",
						code: "KRT"
					}, {
						name: "亚的斯亚贝巴",
						country: "埃塞俄比亚",
						code: "ADD"
					}, {
						name: "阿克拉",
						country: "加纳",
						code: "ACC"
					}, {
						name: "达累斯萨拉姆",
						country: "坦桑尼亚",
						code: "DAR"
					}, {
						name: "塞舌尔",
						country: "塞舌尔共和国",
						code: "SEZ"
					}, {
						name: "阿尔及尔",
						country: "阿尔及利亚",
						code: "ALG"
					}, {
						name: "的黎波里",
						country: "利比亚",
						code: "TIP"
					}, {
						name: "阿布贾",
						country: "尼日利亚",
						code: "ABV"
					}, {
						name: "卡萨布兰卡",
						country: "摩洛哥",
						code: "CAS"
					}, {
						name: "突尼斯",
						country: "突尼斯",
						code: "TUN"
					}]
				}],
				title: "非洲热门城市",
				desc: "可直接输入中文名/拼音/英文名/三字码",
				cls: "inter"
			}
		}
	
};
